-- MySQL Script generated by MySQL Workbench
-- Sun May 15 20:29:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_semear
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_semear
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_semear` DEFAULT CHARACTER SET utf8 ;
USE `db_semear` ;

-- -----------------------------------------------------
-- Table `db_semear`.`tb_DadosPC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_semear`.`tb_DadosPC` (
  `idtb_DadosPC` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `telefone` INT(15) NOT NULL,
  `cep` INT(10) NOT NULL,
  `rua` VARCHAR(25) NOT NULL,
  `bairro` VARCHAR(25) NOT NULL,
  `estado` VARCHAR(3) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtb_DadosPC`),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
